name: Generate Snake

on:
  schedule:
    # Запуск каждый день в полночь по UTC
    - cron: "0 0 * * *"
  # Разрешает ручной запуск
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Генерирует SVG файл с анимацией Змейки
      - uses: Platane/snk@master
        id: snake-gif
        with:
          # ВАШ НИКНЕЙМ (Makhkambek)
          github_user_name: Makhkambek 
          gif_out_path: ./output/github-contribution-grid-snake.svg
          
      # Коммитит и пушит сгенерированный файл обратно в репозиторий
      - name: Push to GitHub
        uses: cpina/github-push-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Обновление анимации Змейки
          force: true
