name: Generate Snake

on:
  schedule:
    # Запуск каждый день в полночь по UTC
    - cron: "0 0 * * *"
  # Разрешает ручной запуск
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Обновлено до v3
      
      # Шаг 1: Генерирует SVG файл с анимацией Змейки
      - uses: Platane/snk@master
        id: snake-gif
        with:
          # ВАШ НИКНЕЙМ (Makhkambek)
          github_user_name: Makhkambek 
          gif_out_path: ./output/github-contribution-grid-snake.svg
          
      # Шаг 2: Коммитит и Пушит изменения в репозиторий (ИСПРАВЛЕНО)
      - name: Push new snake file to repository
        uses: ad-m/github-push-action@master # Используем проверенный экшен
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # Убедитесь, что ваша основная ветка называется 'main'
          directory: output 
          force: true
          message: Обновление анимации Змейки
